### ISSUE TITLE
when build repo via "python setup.py install" on linux, leads to an error

### ISSUE THREAD

**Issue by Yaphet-Zhang** [dblalock/bolt#12]
I want to run this repo's program via Python , but an error occurred on my Ubuntu18.04 like following. Can I get your opinion please?

'''
swigging cpp/src/external/eigen/.hg/......
swig -python -c++ -o cpp/src/extenal/eigne/.hg/......Error: Unterminated string constant
error: command 'swig' failed with exit status 1
'''

**Comment by dblalock** [comment]
I think this is the same issue as #4. I'm going to close this and move discussion there, but feel free to reopen if it turns out the problem you're seeing is different.

**Comment by Yaphet-Zhang** [comment]
> I think this is the same issue as #4. I'm going to close this and move discussion there, but feel free to reopen if it turns out the problem you're seeing is different.

Thanks a lot for your reply. I look forward to your solutions that can run on windows or linux in the future.

**Comment by xyzustc** [comment]
> I want to run this repo's program via Python , but an error occurred on my Ubuntu18.04 like following. Can I get your opinion please?
> 
> '''
> swigging cpp/src/external/eigen/.hg/......
> swig -python -c++ -o cpp/src/extenal/eigne/.hg/......Error: Unterminated string constant
> error: command 'swig' failed with exit status 1
> '''

aws g4dn.xlarge,ubuntu 18.04 exactly same question.
