### ISSUE TITLE
Convnet1M is not available.

### ISSUE THREAD

**Issue by deplay** [dblalock/bolt#16]
Convnet1M - 1 million convnet image descriptors
https://github.com/una-dinosauria/stacked-quantizers provide google driver links for Convnet1M
https://drive.google.com/file/d/0BxWzojlLp259aUt4Z1ZCMzVDQlk/view?usp=sharing
This url is no longer available.
Would you mind providing a valid link to download this dataset so that I can reproduce your experiments.Thank you!

**Comment by dblalock** [comment]
Hmm...I'm actually not sure where it went if it's gone from there. Maybe @[una-dinosauria](https://github.com/una-dinosauria) knows.

Also, note that this dataset was only used in the experiments for the Bolt paper in 2017, and not in the MADDNESS paper. So you might not need it, depending on your goals.

**Comment by dblalock** [comment]
Update: went ahead and added these files under [experiments/assets](https://github.com/dblalock/bolt/tree/master/experiments/assets) since they don't seem to be hosted anywhere else anymore. Thanks for bringing up this issue @deplay!
