### ISSUE TITLE
I‘m beginner，want to run this program in C++

### ISSUE THREAD

**Issue by a3413209** [dblalock/bolt#18]
Hello, I‘m beginner，want to run this program in C++，install BAZEL according to your instructions，and bazel run :main，the above was successful，I would like to ask if you have a complete test code for C++，just like：Input two matrices and output a multiplication result。Additional question，bazel run :main finish，What is the result of bazel run :main？ Is Bolt's library function API？

**Comment by dblalock** [comment]
So I'm not quite sure what you mean...does [this question/answer](https://github.com/dblalock/bolt/issues/17) help?

**Comment by a3413209** [comment]
Where is the code entry and how do I enter my own two matrices? like this question...

**Comment by dblalock** [comment]
Hi @a3413209. Closing this as a duplicate of #17. Feel free to reopen if you have more questions.
