### ISSUE TITLE
Requst for the data

### ISSUE THREAD

**Issue by chituma110** [dblalock/bolt#24]
Could you please share your experiment data in the script (matmul_datasets.py)? You may upload the following *.npy files and give me a link, I can download them myself.
![image](https://user-images.githubusercontent.com/7559308/136650624-aab25ad0-ba5e-4058-9303-ef25a2c60b26.png)
![image](https://user-images.githubusercontent.com/7559308/136650633-5ca70ff6-ebb4-423b-ba91-d43f5ea21ef5.png)

**Comment by dblalock** [comment]
Hi @chituma110. Thanks for the bug report. I've added these files under [experiments/assets](https://github.com/dblalock/bolt/tree/master/experiments/assets). Let me know if you hit any more issues!
