### ISSUE TITLE
AttributeError: module 'sklearn.linear_model' has no attribute 'ridge'

### ISSUE THREAD

**Issue by joshua-doolan** [dblalock/bolt#27]
When learning the clusters for MithralEncoder, at this line I ran into the following issue:

https://github.com/dblalock/bolt/blob/99dfffb1e2c5c43cfd1d7746f0dee6b350981bbd/experiments/python/clusterize.py#L890

`AttributeError: module 'sklearn.linear_model' has no attribute 'ridge' `

Upon inspection, it seems that perhaps modifying the line to replace `.ridge.Ridge` with either `.Ridge` or `._ridge.Ridge` may fix the issue. Is it possible there is an sklearn version mismatch with my installation?

**Comment by dblalock** [comment]
Fixed. Thanks for the bug report @joshua-doolan!
