### ISSUE TITLE
Unable to install bolt

### ISSUE THREAD

**Issue by XiaoConstantine** [dblalock/bolt#8]
OS: macOS Big Sur 11.5.2
Python: 2.7.17

Follow the steps mentioned in README, brew install swig, then numpy, last setup install

Still getting following error:
```bash
swigging cpp/src/external/eigen/.hg/store/data/_c_test_custom.cmake.in.i to cpp/src/external/eigen/.hg/store/data/_c_test_custom.cmake.in_wrap.cpp
swig -python -c++ -o cpp/src/external/eigen/.hg/store/data/_c_test_custom.cmake.in_wrap.cpp cpp/src/external/eigen/.hg/store/data/_c_test_custom.cmake.in.i
cpp/src/external/eigen/.hg/store/data/_c_test_custom.cmake.in.i:1: Error: Illegal token '�'.
cpp/src/external/eigen/.hg/store/data/_c_test_custom.cmake.in.i:1: Error: Syntax error in input(1).
error: command 'swig' failed with exit status 1
```

Any idea what's going on here? I m not familiar with this swig thing

**Comment by dblalock** [comment]
I think this is the same issue as #4, so I'm going to go ahead and close this so we can get all the discussion in one place. Feel free to reopen if it looks like you're hitting a different problem though.

**Comment by XiaoConstantine** [comment]
Sounds good, will follow up on the other PR then. Thank you @dblalock !
