### ISSUE TITLE
"python setup.py install" get problem

### ISSUE THREAD

**Issue by dumppool** [dblalock/bolt#9]
swigging python/bolt/native.i to python/bolt/native_wrap.cpp
swig -python -c++ -o python/bolt/native_wrap.cpp python/bolt/native.i
python/bolt/config.i:51: Error: Syntax error in input(1).
error: command 'swig' failed with exit status 1

OS: centos linux , python 3.7

**Comment by dblalock** [comment]
Thanks for filing this! I'm going to consolidate this into #4, but feel free to reopen if you think your issue is different.
